#
# 特に説明の無いファイルパスは Profile フォルダーからの相対パスです。
#

[Engine]

# 将棋ソフトの表示名です。 後ろにバージョン番号が付くなどの加工があることがあります。
Name = "Kifuwarane"

# 将棋ソフトの制作者名です。
Author = "Satoshi TAKAHASHI"

[Resources]

LogDirectory = "../Logs"

# 道１８７
Michi187 = "data_michi187.csv"

# 駒の配役１８１
Haiyaku181 = "data_haiyaku185_UTF-8.csv"

# 強制転成表(入力)
InputForcePromotion = "data_forcePromotion_UTF-8.csv"

# 強制転成表(出力)
OutputForcePromotion = "強制転成表.html"

# 配役転換表(入力)
InputPieceTypeToHaiyaku = "data_syuruiToHaiyaku.csv"

# 配役転換表(出力)
OutputPieceTypeToHaiyaku = "配役転換表.html"

# GUIから呼び出す将棋エンジン。
# GUI の .exe ファイルからの相対パス。
#
# 旧 bin/Release/settei.xml 
# <?xml version="1.0" encoding="UTF-8"?>
# <kifunarabe setteiFileVer="0.00.0">
#   <!--v(^-^)vｲｪｰｲ☆ 『将棋ＧＵＩ きふならべ』の設定ファイルなんだぜ☆！ 今は一番上に書いてある ＜shogiEngine＞ を見に行くぜ☆-->
#   <shogiEngine file="shogiEngine.exe" />
# </kifunarabe>
#
Engine = "./Grayscale.Kifuwarane.Engine.exe"

# Log file stem.

HaichiTenkanHyoOnlyDataLog = "../Logs/Debug_配役転換表Load(1)_データ行のみ"
HaichiTenkanHyoAllLog = "../Logs/Debug_配役転換表Load(2)"

# Data file stem.

#
# Resources.LogDirectory からの相対パスだぜ☆（＾～＾） 拡張子は付けるなだぜ☆（＾～＾）
#
[Logs]

GuiRecordLog = "将棋GUI_棋譜読取"
LibLog = "Lib"
LinkedListLog = "LinkedList"
EngineRecordLog = "将棋エンジン_棋譜読取"
GuiPaint = "将棋GUI_ペイント"
LegalMoveLog = "合法手"
LegalMoveEvasionLog = "リーガルムーブ(被王手時)"
GenMoveLog = "指し手生成ルーチン"
ErrorLog = "エラー"
