[Engine]

# 将棋ソフトの表示名です。 後ろに ` Bld2` のようなビルド番号が付くものもあります。
Name = "Kifuwarane"

# 将棋ソフトの制作者名です。
Author = "Satoshi TAKAHASHI"

[Resources]

# 特に説明の無いものは Profile フォルダーからの相対パスです。
# 道１８７
Michi187 = "data_michi187.csv"

# 駒の配役１８１
Haiyaku181 = "data_haiyaku185_UTF-8.csv"

# 強制転成表(入力)
InputForcePromotion = "data_forcePromotion_UTF-8.csv"

# 強制転成表(出力)
OutputForcePromotion = "強制転成表.html"

# 配役転換表(入力)
InputPieceTypeToHaiyaku = "data_syuruiToHaiyaku.csv"

# 配役転換表(出力)
OutputPieceTypeToHaiyaku = "配役転換表.html"

# GUIから呼び出す将棋エンジン。
# GUI の .exe ファイルからの相対パス。
#
# 旧 bin/Release/settei.xml 
# <?xml version="1.0" encoding="UTF-8"?>
# <kifunarabe setteiFileVer="0.00.0">
#   <!--v(^-^)vｲｪｰｲ☆ 『将棋ＧＵＩ きふならべ』の設定ファイルなんだぜ☆！ 今は一番上に書いてある ＜shogiEngine＞ を見に行くぜ☆-->
#   <shogiEngine file="shogiEngine.exe" />
# </kifunarabe>
#
Engine = "./Grayscale.KifuwaraneEngine.exe"
